name: CI Build and Test Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
    - name: Checkout Code Repository
      uses: actions/checkout@v4
    
    - name: Set Up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install Project Dependencies
      run: npm ci

    - name: Execute Tests
      run: npm run test-coverage

    - name: Build Library
      run: npm run build-lib
